const mockArticles = [
    {
        id: 1,
        title: "10 Hidden Gems in Kyoto You Must Visit",
        excerpt: "Discover the serenity of lesser-known temples and the charm of quiet alleyways away from the bustling tourist spots.",
        content: "Kyoto is a city that feels like it's trapped in time. Beyond the famous Kinkaku-ji and Fushimi Inari, there are countless hidden gems waiting to be explored. From the quiet moss gardens of Gio-ji to the stunning views from the less-crowded Otagi Nenbutsu-ji, these spots offer a more intimate connection with the city's spiritual heritage. Walking through the narrow streets of Gion at dusk, you might catch a glimpse of a geiko disappearing into a wooden doorway, a reminder of the traditions that still thrive here.",
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop",
        category: "Travel Tips",
        author: "Elena Rodriguez",
        authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
        date: "Oct 24, 2026",
        isFeatured: true,
        quote: "Travel is not just about seeing new places, but about seeing things with new eyes.",
    },
    {
        id: 2,
        title: "The Future of Minimalist UI Design",
        excerpt: "Why reducing visual noise increases user engagement and how to implement it effectively in your next project.",
        content: "In an era of information overload, minimalism in UI design has become more than just an aesthetic choice; it's a necessity. By stripping away non-essential elements, designers can guide users toward their goals more efficiently. The key is to balance simplicity with functionality—ensuring that the absence of clutter doesn't lead to a lack of clarity. Use of white space, subtle typography, and a limited color palette can create a focused, premium feel that resonates with modern users.",
        image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
        category: "Design",
        author: "David Chen",
        authorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
        date: "Oct 22, 2026",
        isFeatured: false,
        quote: "Simplicity is the ultimate sophistication.",
    },
    {
        id: 3,
        title: "Mastering the Art of French Baking at Home",
        excerpt: "From perfect croissants to delicate macarons, learn the secrets of pâtisserie from a master baker.",
        content: "French baking is often seen as intimidating, but with the right techniques and a bit of patience, anyone can master it at home. The secret lies in the quality of ingredients—high-fat butter, fine flour, and fresh eggs make all the difference. Whether you're laminating dough for croissants or timing your macarons to get that perfect 'foot,' the process is as rewarding as the final result. Understanding the science behind the rise and the chemistry of the caramelization is key to becoming a true pâtissier.",
        image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=600&auto=format&fit=crop",
        category: "Food",
        author: "Sophie Laurent",
        authorImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&auto=format&fit=crop",
        date: "Oct 20, 2026",
        isFeatured: false,
        quote: "Baking is a science, but eating is an art.",
    },
    {
        id: 4,
        title: "Sustainable Living: Small Changes, Big Impact",
        excerpt: "Practical tips for reducing your carbon footprint without drastically altering your lifestyle.",
        content: "Sustainability doesn't have to mean radical change. Small, consistent adjustments in our daily lives can lead to a significant collective impact. From switching to reusable bags and containers to choosing local, seasonal produce, every action counts. Reducing energy consumption at home, composting organic waste, and supporting ethical brands are all ways to move toward a more sustainable future. It's about being conscious of our choices and their long-term effects on the planet.",
        image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=800&auto=format&fit=crop",
        category: "Environment",
        author: "Mark Johnson",
        authorImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop",
        date: "Oct 18, 2026",
        isFeatured: true,
        quote: "We do not inherit the earth from our ancestors, we borrow it from our children.",
    },
    {
        id: 5,
        title: "Understanding Server Actions in React 19",
        excerpt: "A deep dive into how Server Actions simplify data mutation and form handling in modern React applications.",
        content: "React 19 brings a suite of powerful features, none more transformative than Server Actions. By allowing developers to define functions that run on the server but can be called directly from client components, React is bridging the gap between frontend and backend. This eliminates the need for manual API route creation for many use cases, simplifying form handling and data updates. Combined with the new `useActionState` and `useFormStatus` hooks, Server Actions provide a seamless, type-safe development experience.",
        image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=800&auto=format&fit=crop",
        category: "Technology",
        author: "Sarah Kim",
        authorImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop",
        date: "Oct 15, 2026",
        isFeatured: false,
        quote: "The best way to predict the future is to invent it.",
    },
    {
        id: 6,
        title: "The Ultimate Guide to Street Photography",
        excerpt: "Techniques for capturing candid moments and telling compelling stories through your lens in urban environments.",
        content: "Street photography is the art of capturing life in its rawest, most unscripted form. It requires a keen eye, quick reflexes, and a deep respect for the subjects. The best street photographs are those that tell a story—that freeze a moment in time and evoke an emotional response. Whether it's the play of light and shadow in an alleyway or the expression on a stranger's face, the goal is to find the extraordinary in the ordinary. Mastering the 'invisible' approach is key to capturing genuine moments.",
        image: "https://images.unsplash.com/photo-1669494920898-14cbf6802f1c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG9ydHJhaXQlMjBiYWNrZ3JvdW5kfGVufDB8fDB8fHww",
        category: "Photography",
        author: "Alex Morgan",
        authorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
        date: "Oct 12, 2026",
        isFeatured: true,
        quote: "A photograph is a secret about a secret. The more it tells you the less you know.",
    }
];
export { mockArticles }