version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insightville-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: insightville-backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    restart: always
